import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import './tailwind.css';

import NextUIProvider from '@/components/NextUIProvider';
import { ApolloClientProvider } from '@/graphql/clients/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloClientProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
