import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { PropsWithChildren } from 'react';

import NextUIProvider from '@/components/NextUIProvider';
import { ApolloClientProvider } from '@/graphql/clients/provider';
import { cn } from '@/lib/styles';

import './tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-dvh')}>
        <ApolloClientProvider>
          <NextUIProvider>
            <ThemeProvider attribute="class">{children}</ThemeProvider>
          </NextUIProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
