import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { Toaster } from 'react-hot-toast';

import EventProvider from '@/components/EventProvider';
import NextUIProvider from '@/components/NextUIProvider';
import ThemeProvider from '@/components/ThemeProvider';
import { ApolloClientProvider } from '@/graphql/clients/provider';
import { cn } from '@/lib/styles';
import './tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-dvh')}>
        <ApolloClientProvider>
          <NextUIProvider>
            <ThemeProvider>
              <EventProvider>
                {children}
                <Toaster position="top-right" toastOptions={{ className: 'toast' }} />
              </EventProvider>
            </ThemeProvider>
          </NextUIProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
